baseURL: https://ok-lab-karlsruhe.de
DefaultContentLanguage: de
title: OK Lab Karlsruhe
theme: hugo-cfg
#Disables warnings
disableKinds:
 -taxonomy
 -taxonomyTerm
pluralizeListTitles: false
# tell hugo to get the date from the filename, if possible
frontmatter:
  date: [":filename", ":default"]
ignorefiles: [ "php/*","php/.*", "tools/*","tools/.*"  ]
enableRobotsTXT: True
# disable individual pages via frontmatter: robotsdisallow: True

params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  navbarlogo:
   image: img/CFG_Karlsruhe.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]


languages:
  de:
    languageName: Deutsch
    weight: 1
    contentDir: content/de
    lang: de
    # Used as meta data; describe your site to make Google Bots happy
    description: Webseite des OK Lab Karlsruhe. Offene Daten, offene Verwaltung, Demokratie, Partizipation, Coding, Daten, Codefor Karlsruhe, Freies Wissen
    params:
      hero:
        # Main hero title
        title: OK Lab Karlsruhe
        # Hero subtitle (optional)
        # subtitle: Wir sind ein offenes Stadtlabor und bauen digitale Werkzeuge für alle!
        subtitle: Open Knowledge // Freies Wissen mit digitalen Werkzeugen für alle!  
        # subsubtitle: Mehr InfoDiese Seiten sind noch im Aufbau ...
        #subtitle: Diese Seite ist noch im Aufbau ...
        # Button text
        buttontext: Werde Stadtentwickler*in!
        # Where the main hero button links to
        buttonlink: "mitmachen"
        # Hero image (from static/images/___)
        image: "../img/CfKA Hexagon 3d.svg" # illustrations/worker.svg
      # langiage switch: works, but keep it disabled until translation complete
      switch:
        title: EN
        lang: Englisch
        code: en
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: Über uns
        url: /ueber/
      - title: Projekte
        url: /projekte/
      - title: Mitmachen
        url: /mitmachen
      - title: Code For Germany
        url: https://codefor.de/
        button: false
      section1:
        title: Zivilgesellschaftliches Engagement
        subtitle: Gute Taten mit offenen Daten
        tiles:
        - # title: Design & Entwicklung
          icon: coding
          text:
          url: /mitmachen#entwickler
          buttonText: Entwicklung & Design
        - # title: Cloud integration
          icon: folders
          text:
          url: /mitmachen#politiker
          buttonText: Politik & Verwaltung
        - # title: Add-ons & plugins
          icon: microphone
          text:
          url: /mitmachen#journalist
          buttonText: Journalismus & Unterstützung
      section2:
        subtitle: Freie Software + Offene Daten = <3
        title: open source + open data = <3
        features:
        - title: Offene Daten // Open Data
          text: Offene Daten sind Daten, auf die alle Personen frei zugreifen können und die von allen genutzt, verändert und geteilt werden können. Sie werden in vielen Anwendungen erzeugt und gesammelt, beispielsweise in amtlichen Messungen oder wissenschaftlichen Experimenten.
          # Icon (from /images/illustrations/icons/___.svg)
          icon: laptop-globe
        - title: Offene Verwaltung // Open Government
          text: Politik und Verwaltung sollen geöffnet werden für Bürger*innen, Wirtschaft, Wissenschaft, Kunst und Kultur, um stärkere gemeinschaftliche Belange in einer Kommune zu ermöglichen. Im Fokus stehen dabei Transparenz, Partizipation und Kollaboration.
          icon: doc-sync
        - title: Zivilgesellschaftliche Technik // Civic Tech
          text: Technischen Konzepten können Engagement und Beteiligung von Bürgern fördern, beispielsweise durch entsprechende Kommunikationsplattformen, bessere öffentliche Infrastrukturen und technikbasierte Verbesserungen des Allgemeinwohls.
          icon: mobile-feed
      section3:
        title: Wir nehmen offene Daten
        subtitle: und bauen daraus Anwendungen für Bürger*innen.
        #image: illustrations/cfg-summit-19.png
        # images here are in theme directory below images
        image: sma.jpg
        buttonText: Zu den Projekten
        buttonLink: "/projekte/"
      section4:
        title: Das Konzept der Offenheit
        # subtitle: für 2020
        clients:
        - name: Offene Daten
          quote: Offene Daten sind Daten, auf die alle Personen frei zugreifen können und die von allen genutzt, verändert und geteilt werden können. Sie werden in vielen Anwendungen erzeugt und gesammelt, beispielsweise in amtlichen Messungen oder wissenschaftlichen Experimenten.
          job:
          img: icons/156-stats-dots.svg
        - name: Offene Verwaltung
          quote: Politik und Verwaltung sollen geöffnet werden für Bürger*innen, Wirtschaft, Wissenschaft, Kunst und Kultur, um stärkere gemeinschaftliche Belange in einer Kommune zu ermöglichen. Im Fokus stehen dabei Transparenz, Partizipation und Kollaboration.
          job:
          img: icons/033-books.svg
        - name: Zivilgesellschaftliche Technik
          quote: Technische Konzepte können Engagement und Beteiligung von Bürgern fördern, beispielsweise durch entsprechende Kommunikationsplattformen, bessere öffentliche Infrastrukturen und technikbasierte Verbesserungen des Allgemeinwohls.
          job:
          img: icons/087-display.svg
      section5: true
      footer:
        logo: /img/okf.svg
        logourl: https://okfn.de/
        #logo: /img/CFG_Karlsruhe_white.svg
        # Social Media Title
        socialmediatitle: Folge uns!
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
          # Icons are from Font Awesome. use fa-<name> as item 
        - link: mailto:info@ok-lab-karlsruhe.de
          icon: envelope
          # Icons are from Font Awesome
        - link: https://github.com/CodeforKarlsruhe
          icon: github
        - link: https://twitter.com/code4karlsruhe
          icon: twitter
        bulmalogo: true
        quicklinks:
          column1:
            title: "Rechtliches"
            links:
            - text: Impressum
              link: /impressum/
            - text: Datenschutz
              link: /impressum/#datenschutzerklaerung
            - text: Grundsätze
              link: /grundsaetze/
          column2:
            title: "Werkzeugkoffer"
            links:
            - text: Github OKF (extern)
              link: https://github.com/okfde
            - text: opendatahandbook.org
              link: https://opendatahandbook.org/
            - text: ABC der Offenheit
              link: https://upload.wikimedia.org/wikipedia/commons/a/a9/ABC_der_Offenheit_-_Brosch%C3%BCre_%282019%29.pdf
          column3:
            title: "Über uns"
            links:
            - text: Projekte
              link: /projekte/
            - text: Mitmachen
              link: /mitmachen/


  en:
    languageName: English
    weight: 2
    contentDir: content/en
    lang: en
    # Used as meta data; describe your site to make Google Bots happy
    description: Website of the OK Lab Karlsruhe. Open Data, Open Government, Democrycy, Participation, Civic Tech, Coding, Daten, Codefor Karlsruhe, Open Knowledge
    params:
      hero:
        # Main hero title
        title: OK Lab Karlsruhe
        # Hero subtitle (optional)
        subtitle: Open Knowledge with digital tools for all!
        ## subsubtitle: This site is work in progress. Stay tuned ...
        # Button text
        buttontext: Improve your city!
        # Where the main hero button links to
        buttonlink: "/en/mitmachen"
        # Hero image (from static/images/___)
        image: "../img/CfKA Hexagon 3d.svg" # illustrations/worker.svg
      # langiage switch: works, but keep it disabled until translation complete
      switch:
        title: DE
        lang: German
        code: de
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: About
        url: /en/ueber/
      - title: Projects
        url: /en/projekte/
      - title: Join us
        url: /en/mitmachen/
      - title: Code For Germany
        url: https://codefor.de/
        button: false
      section1:
        title: Get Involved in Civic Tech
        subtitle: Good deeds with open data
        tiles:
        - # title: Design & Entwicklung
          icon: coding
          text:
          url: /en/mitmachen#entwickler
          buttonText: Design & Development
        - # title: Cloud integration
          icon: folders
          text:
          url: /en/mitmachen#politiker
          buttonText: Politics & Administration
        - # title: Add-ons & plugins
          icon: microphone
          text:
          url: /en/mitmachen#journalist
          buttonText: Journalism & Support
      section2:
        title: Open Source + Open Data = <3
        subtitle: Free Software + Open Data = <3
        features:
        - title: Open Data
          text: Open data is data that everyone can freely access and that can be used, changed and shared by everyone. They are generated and collected in many applications, for example in official measurements or scientific experiments.
          # Icon (from /images/illustrations/icons/___.svg)
          icon: laptop-globe
        - title: Open Government
          text: Politics and administration should be opened to citizens, business, science, art and culture in order to enable stronger common interests in a community. The focus is on transparency, participation and collaboration.
          icon: doc-sync
        - title: Civic Tech
          text: Technical concepts can promote engagement and participation of citizens, for example through appropriate communication platforms, better public infrastructures and technology-based improvements in the common good.
          icon: mobile-feed
      section3:
        title: We use open data
        subtitle: to build applications for citicens.
        #image: illustrations/cfg-summit-19.png
        # images here are in theme directory below images
        image: sma.jpg
        buttonText: The projects
        buttonLink: "/en/projekte/"
      section4:
        title: The Concept of Openness
        #subtitle: in 2020
        clients:
        - name: Open Data
          quote: Open data is data that everyone can freely access and that can be used, changed and shared by everyone. They are generated and collected in many applications, for example in official measurements or scientific experiments.
          job:
          img: icons/156-stats-dots.svg
        - name: Open Government
          quote: Politics and administration should be opened to citizens, business, science, art and culture in order to enable stronger common interests in a community. The focus is on transparency, participation and collaboration.
          job:
          img: icons/033-books.svg
        - name: Civic Tech
          quote: Technical concepts can promote engagement and participation of citizens, for example through appropriate communication platforms, better public infrastructures and technology-based improvements in the common good.
          job:
          img: icons/087-display.svg
      section5: true
      footer:
        #logo: /img/CFG_Karlsruhe_white.svg
        logo: /img/okf.svg
        logourl: https://okfn.de/
        # Social Media Title
        socialmediatitle: Follow us!
        # Social media links (GitHub, Twitter, etc.). All are optional.
        socialmedia:
        - link: mailto:info@ok-lab-karlsruhe.de
          icon: envelope
        - link: https://github.com/CodeforKarlsruhe
          icon: github
        - link: https://twitter.com/code4karlsruhe
          icon: twitter
        bulmalogo: true
        quicklinks:
          column1:
            title: "Legal stuff"
            links:
            - text: Imprint
              link: /en/impressum/
            - text: Data protection
              link: /en/impressum/#datenschutzerklaerung
            - text: Code of Conduct
              link: /en/grundsaetze/
          column2:
            title: "Toolset"
            links:
            - text: Github OKF (extern)
              link: https://github.com/okfde
            - text: opendatahandbook.org
              link: https://opendatahandbook.org/
            - text: ABC der Offenheit
              link: https://upload.wikimedia.org/wikipedia/commons/a/a9/ABC_der_Offenheit_-_Brosch%C3%BCre_%282019%29.pdf
          column3:
            title: "About"
            links:
            - text: Projects
              link: /en/projekte/
            - text: Join Us
              link: /en/mitmachen/


